In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
S=pd.read_csv("D:\\Zaids Work\\Signal processing with AI\\new data\\seattle-weather.csv")
S

date  precipitation  temp_max  temp_min  wind  weather
0     2012-01-01            0.0      12.8       5.0   4.7  drizzle
1     2012-01-02           10.9      10.6       2.8   4.5     rain
2     2012-01-03            0.8      11.7       7.2   2.3     rain
3     2012-01-04           20.3      12.2       5.6   4.7     rain
4     2012-01-05            1.3       8.9       2.8   6.1     rain
...          ...            ...       ...       ...   ...      ...
1456  2015-12-27            8.6       4.4       1.7   2.9     rain
1457  2015-12-28            1.5       5.0       1.7   1.3     rain
1458  2015-12-29            0.0       7.2       0.6   2.6      fog
1459  2015-12-30            0.0       5.6      -1.0   3.4      sun
1460  2015-12-31            0.0       5.6      -2.1   3.5      sun

[1461 rows x 6 columns]

In [6]:
S.weather.unique()


array(['drizzle', 'rain', 'sun', 'snow', 'fog'], dtype=object)

In [7]:
S.dtypes

date              object
precipitation    float64
temp_max         float64
temp_min         float64
wind             float64
weather           object
dtype: object

In [8]:
S.isnull().sum()

date             0
precipitation    0
temp_max         0
temp_min         0
wind             0
weather          0
dtype: int64

In [9]:
S.weather.value_counts()

weather
rain       641
sun        640
fog        101
drizzle     53
snow        26
Name: count, dtype: int64

In [10]:
S.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1461 entries, 0 to 1460
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   date           1461 non-null   object 
 1   precipitation  1461 non-null   float64
 2   temp_max       1461 non-null   float64
 3   temp_min       1461 non-null   float64
 4   wind           1461 non-null   float64
 5   weather        1461 non-null   object 
dtypes: float64(4), object(2)
memory usage: 68.6+ KB


In [11]:
S.weather[:144]

0      drizzle
1         rain
2         rain
3         rain
4         rain
        ...   
139        sun
140       rain
141       rain
142       rain
143       rain
Name: weather, Length: 144, dtype: object

In [12]:
S.shape

(1461, 6)

In [13]:
S.describe()

precipitation     temp_max     temp_min         wind
count    1461.000000  1461.000000  1461.000000  1461.000000
mean        3.029432    16.439083     8.234771     3.241136
std         6.680194     7.349758     5.023004     1.437825
min         0.000000    -1.600000    -7.100000     0.400000
25%         0.000000    10.600000     4.400000     2.200000
50%         0.000000    15.600000     8.300000     3.000000
75%         2.800000    22.200000    12.200000     4.000000
max        55.900000    35.600000    18.300000     9.500000

In [14]:
#preprocessing part
#split the data into input and targets
x=S.iloc[:,1:-1]
y=S.iloc[:,-1:]
x

precipitation  temp_max  temp_min  wind
0               0.0      12.8       5.0   4.7
1              10.9      10.6       2.8   4.5
2               0.8      11.7       7.2   2.3
3              20.3      12.2       5.6   4.7
4               1.3       8.9       2.8   6.1
...             ...       ...       ...   ...
1456            8.6       4.4       1.7   2.9
1457            1.5       5.0       1.7   1.3
1458            0.0       7.2       0.6   2.6
1459            0.0       5.6      -1.0   3.4
1460            0.0       5.6      -2.1   3.5

[1461 rows x 4 columns]

In [15]:
#apply label encoding onto weather column
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder() #create an object
y=le.fit_transform(y) #assign numbers based on alphabetical order
y

c:\Users\MOHAMMED ZAID\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([0, 2, 2, ..., 1, 4, 4])

## standardize the data

In [ ]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
x.iloc[:,:]=ss.fit_transf                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           orm(x)
x

precipitation  temp_max  temp_min      wind
0         -0.453650 -0.495299 -0.644212  1.014980
1          1.178598 -0.794731 -1.082347  0.875833
2         -0.333852 -0.645015 -0.206077 -0.654780
3          2.586224 -0.576962 -0.524720  1.014980
4         -0.258978 -1.026111 -1.082347  1.989006
...             ...       ...       ...       ...
1456       0.834179 -1.638585 -1.301414 -0.237340
1457      -0.229029 -1.556922 -1.301414 -1.350513
1458      -0.453650 -1.257490 -1.520481 -0.446060
1459      -0.453650 -1.475259 -1.839125  0.110527
1460      -0.453650 -1.475259 -2.058192  0.180100

[1461 rows x 4 columns]

In [25]:
#train test split 
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.25,random_state=0)
print(xtrain.shape)
print(xtest.shape)
print(ytrain.shape)
print(ytest.shape)

(1095, 4)
(366, 4)
(1095,)
(366,)


In [26]:
from sklearn.neighbors import KNeighborsClassifier
KNN=KNeighborsClassifier(n_neighbors=5,p=2)
#p=2 euclidean distance
#p=1 manhattan distance
#train
KNN.fit(xtrain,ytrain)

KNeighborsClassifier()

In [27]:
#testing
ypredict=KNN.predict(xtest)
ypredict[:10]

array([4, 2, 2, 4, 0, 2, 2, 2, 4, 4])

In [28]:

ytest[:10]

array([4, 4, 2, 4, 4, 2, 2, 2, 1, 2])

In [29]:
from sklearn.metrics import accuracy_score,confusion_matrix
cm=confusion_matrix(ytest,ypredict)
cm

array([[  1,   1,   3,   0,   6],
       [  1,   5,   4,   0,  21],
       [  0,   3, 128,   0,  24],
       [  0,   0,   3,   1,   2],
       [  5,  17,  26,   0, 115]])

In [30]:
accuracy=accuracy_score(ytest,ypredict)
accuracy


0.6830601092896175

## KNN ALGORITHM

-it is a non parametric algorithm which does not make any assumptions
-it is one of the simplest and easy to implementable algorithm
-it is also called as lazy algorithm, as it does not learns anything during training phase

## KNN STEPS

-compute the distance between the test point vs all training samples
-(use any distance measure like euclidean,manhattan ,minkowski)
-arrange the distances computed in ascending order
-select the k value 
-vote for majority
-class having higher votes in the outcome 


## Decision Tree


 - Decision tree works on the concept of recursive partitioning of the data
 - by using best attribue to make decision
 - i want to buy the mobile what feautures to look for
 - write any 5 feautures you think are required
   - camera,price,processor,ram,brand

In [ ]:
from sklearn.tree import DecisionTreeClassifier
DTC = DecisionTreeClassifier(criterion="entropy",random_state=0)

#Train the model
DTC.fit(xtrain,ytrain)

#Testing
Ypredict = DTC.predict(xtest)

from sklearn.metrics import accuracy_score,confusion_matrix

cm = confusion_matrix(ytest,Ypredict)
print(cm)
print()
accu = accuracy_score(ytest,Ypredict)
print("Accuracy_score: ",accu)

[[  1   1   0   0   9]
 [  3   7   2   0  19]
 [  0   2 143   1   9]
 [  0   0   3   3   0]
 [ 21  19   7   0 116]]

Accuracy_score:  0.7377049180327869


In [ ]:
feature_importance=DTC.feature_importances_
plt.figure(figsize=(10,6))
